
from __future__ import annotations

from copy import deepcopy
from typing import Any

SAN_JOSE_LUXURY_DEMO_LISTINGS: list[dict[str, Any]] = [
    {
        "id": "demo:sj-almaden-estate-001",
        "source": "demo_seed",
        "mode": "sale",
        "title": "Almaden Valley hillside residence",
        "address": "Demo home near Almaden Expressway and Camden Avenue",
        "city": "San Jose",
        "state": "CA",
        "zip_code": "95123",
        "latitude": 37.2445,
        "longitude": -121.8526,
        "distance_from_search_miles": None,
        "price": 1849000,
        "bedrooms": 4,
        "bathrooms": 3,
        "square_feet": 2840,
        "property_type": "Single Family",
        "description": "Seeded demo cache record for a luxury style San Jose search. It is used only when live provider data is unavailable or returns no records.",
        "images": [
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=80",
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=80"
        ],
        "source_url": None,
        "provider": "Seeded demo cache",
        "contact_name": None,
        "contact_email": None,
        "contact_phone": None,
        "days_on_market": 12,
        "listed_date": None,
        "listing_type": "Demo sale preview",
        "hoa_fee": 0,
        "mls_name": None,
        "mls_number": None,
        "market": {"median_price": 1450000, "median_price_per_sqft": 760, "days_on_market": 18, "source": "Demo market snapshot"},
        "neighborhood": {
            "walkability": {"walkability_score": 76, "food": 8, "grocery": 2, "parks": 4, "transit": 3, "nearest_park_miles": 0.4, "nearest_grocery_miles": 0.8, "nearest_transit_miles": 0.5, "source": "Seeded demo amenity snapshot"},
            "schools": {"source": "Seeded demo school snapshot", "nearby_school_count": 5, "avg_rating_10": 8.2, "nearest_school_miles": 0.7, "schools": []},
            "crime": {"source": "Seeded demo safety snapshot", "safety_score": 78, "incidents_count": 7, "safety_label": "lower reported incident signal"}
        },
        "commute": {},
        "scores": {},
        "reasons": ["Available from the seeded demo cache so the page is grounded during local presentations."]
    },
    {
        "id": "demo:sj-blossom-valley-modern-002",
        "source": "demo_seed",
        "mode": "sale",
        "title": "Blossom Valley modern family home",
        "address": "Demo home near Blossom Hill Road",
        "city": "San Jose",
        "state": "CA",
        "zip_code": "95123",
        "latitude": 37.2501,
        "longitude": -121.8303,
        "distance_from_search_miles": None,
        "price": 1625000,
        "bedrooms": 4,
        "bathrooms": 2.5,
        "square_feet": 2420,
        "property_type": "Single Family",
        "description": "Seeded demo cache record with strong school, park, and commute signals for San Jose relocation comparisons.",
        "images": [
            "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1400&q=80",
            "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=80"
        ],
        "source_url": None,
        "provider": "Seeded demo cache",
        "contact_name": None,
        "contact_email": None,
        "contact_phone": None,
        "days_on_market": 19,
        "listed_date": None,
        "listing_type": "Demo sale preview",
        "hoa_fee": 75,
        "mls_name": None,
        "mls_number": None,
        "market": {"median_price": 1450000, "median_price_per_sqft": 760, "days_on_market": 18, "source": "Demo market snapshot"},
        "neighborhood": {
            "walkability": {"walkability_score": 81, "food": 10, "grocery": 3, "parks": 5, "transit": 4, "nearest_park_miles": 0.3, "nearest_grocery_miles": 0.6, "nearest_transit_miles": 0.4, "source": "Seeded demo amenity snapshot"},
            "schools": {"source": "Seeded demo school snapshot", "nearby_school_count": 6, "avg_rating_10": 8.0, "nearest_school_miles": 0.5, "schools": []},
            "crime": {"source": "Seeded demo safety snapshot", "safety_score": 74, "incidents_count": 9, "safety_label": "moderate low incident signal"}
        },
        "commute": {},
        "scores": {},
        "reasons": ["Strong seeded school and walkability signals for an easy demo comparison."]
    },
    {
        "id": "demo:sj-silver-creek-003",
        "source": "demo_seed",
        "mode": "sale",
        "title": "Silver Creek view estate",
        "address": "Demo home near Silver Creek Valley Road",
        "city": "San Jose",
        "state": "CA",
        "zip_code": "95138",
        "latitude": 37.2794,
        "longitude": -121.7774,
        "distance_from_search_miles": None,
        "price": 2895000,
        "bedrooms": 5,
        "bathrooms": 4.5,
        "square_feet": 4310,
        "property_type": "Single Family",
        "description": "Seeded demo cache record for a higher budget luxury search with larger square footage and hillside views.",
        "images": [
            "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1400&q=80",
            "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1400&q=80"
        ],
        "source_url": None,
        "provider": "Seeded demo cache",
        "contact_name": None,
        "contact_email": None,
        "contact_phone": None,
        "days_on_market": 31,
        "listed_date": None,
        "listing_type": "Demo sale preview",
        "hoa_fee": 295,
        "mls_name": None,
        "mls_number": None,
        "market": {"median_price": 1880000, "median_price_per_sqft": 715, "days_on_market": 24, "source": "Demo market snapshot"},
        "neighborhood": {
            "walkability": {"walkability_score": 58, "food": 4, "grocery": 1, "parks": 6, "transit": 1, "nearest_park_miles": 0.2, "nearest_grocery_miles": 1.4, "nearest_transit_miles": 1.8, "source": "Seeded demo amenity snapshot"},
            "schools": {"source": "Seeded demo school snapshot", "nearby_school_count": 4, "avg_rating_10": 8.6, "nearest_school_miles": 1.0, "schools": []},
            "crime": {"source": "Seeded demo safety snapshot", "safety_score": 83, "incidents_count": 5, "safety_label": "low reported incident signal"}
        },
        "commute": {},
        "scores": {},
        "reasons": ["Largest seeded home in the shortlist with high safety and school scores."]
    },
    {
        "id": "demo:sj-willow-glen-004",
        "source": "demo_seed",
        "mode": "sale",
        "title": "Willow Glen renovated craftsman",
        "address": "Demo home near Lincoln Avenue",
        "city": "San Jose",
        "state": "CA",
        "zip_code": "95125",
        "latitude": 37.3012,
        "longitude": -121.8974,
        "distance_from_search_miles": None,
        "price": 2149000,
        "bedrooms": 4,
        "bathrooms": 3,
        "square_feet": 2685,
        "property_type": "Single Family",
        "description": "Seeded demo cache record with strong walkability, restaurants, grocery access, and neighborhood character.",
        "images": [
            "https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1400&q=80",
            "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=80"
        ],
        "source_url": None,
        "provider": "Seeded demo cache",
        "contact_name": None,
        "contact_email": None,
        "contact_phone": None,
        "days_on_market": 9,
        "listed_date": None,
        "listing_type": "Demo sale preview",
        "hoa_fee": 0,
        "mls_name": None,
        "mls_number": None,
        "market": {"median_price": 1675000, "median_price_per_sqft": 835, "days_on_market": 16, "source": "Demo market snapshot"},
        "neighborhood": {
            "walkability": {"walkability_score": 92, "food": 18, "grocery": 5, "parks": 6, "transit": 7, "nearest_park_miles": 0.2, "nearest_grocery_miles": 0.3, "nearest_transit_miles": 0.2, "source": "Seeded demo amenity snapshot"},
            "schools": {"source": "Seeded demo school snapshot", "nearby_school_count": 7, "avg_rating_10": 7.6, "nearest_school_miles": 0.4, "schools": []},
            "crime": {"source": "Seeded demo safety snapshot", "safety_score": 68, "incidents_count": 12, "safety_label": "moderate incident signal"}
        },
        "commute": {},
        "scores": {},
        "reasons": ["Best seeded walkability option for cafes, parks, grocery, and transit proximity."]
    },
    {
        "id": "demo:los-gatos-estate-005",
        "source": "demo_seed",
        "mode": "sale",
        "title": "Los Gatos ridge estate",
        "address": "Demo home near Los Gatos Boulevard",
        "city": "Los Gatos",
        "state": "CA",
        "zip_code": "95032",
        "latitude": 37.2358,
        "longitude": -121.9624,
        "distance_from_search_miles": None,
        "price": 3485000,
        "bedrooms": 5,
        "bathrooms": 5,
        "square_feet": 5120,
        "property_type": "Single Family",
        "description": "Seeded demo cache record for luxury relocation beyond San Jose within the requested search radius.",
        "images": [
            "https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1400&q=80",
            "https://images.unsplash.com/photo-1598228723793-52759bba239c?auto=format&fit=crop&w=1400&q=80"
        ],
        "source_url": None,
        "provider": "Seeded demo cache",
        "contact_name": None,
        "contact_email": None,
        "contact_phone": None,
        "days_on_market": 27,
        "listed_date": None,
        "listing_type": "Demo sale preview",
        "hoa_fee": 0,
        "mls_name": None,
        "mls_number": None,
        "market": {"median_price": 2650000, "median_price_per_sqft": 895, "days_on_market": 21, "source": "Demo market snapshot"},
        "neighborhood": {
            "walkability": {"walkability_score": 70, "food": 12, "grocery": 3, "parks": 8, "transit": 2, "nearest_park_miles": 0.1, "nearest_grocery_miles": 0.7, "nearest_transit_miles": 0.9, "source": "Seeded demo amenity snapshot"},
            "schools": {"source": "Seeded demo school snapshot", "nearby_school_count": 6, "avg_rating_10": 9.1, "nearest_school_miles": 0.9, "schools": []},
            "crime": {"source": "Seeded demo safety snapshot", "safety_score": 86, "incidents_count": 4, "safety_label": "low reported incident signal"}
        },
        "commute": {},
        "scores": {},
        "reasons": ["Premium seeded option with strongest safety and school balance."]
    },
    {
        "id": "demo:cupertino-modern-006",
        "source": "demo_seed",
        "mode": "sale",
        "title": "Cupertino modern smart home",
        "address": "Demo home near Stevens Creek Boulevard",
        "city": "Cupertino",
        "state": "CA",
        "zip_code": "95014",
        "latitude": 37.3230,
        "longitude": -122.0322,
        "distance_from_search_miles": None,
        "price": 2988000,
        "bedrooms": 4,
        "bathrooms": 3.5,
        "square_feet": 3160,
        "property_type": "Single Family",
        "description": "Seeded demo cache record for a Silicon Valley commute and top school oriented household.",
        "images": [
            "https://images.unsplash.com/photo-1600607687644-c7171b42498b?auto=format&fit=crop&w=1400&q=80",
            "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1400&q=80"
        ],
        "source_url": None,
        "provider": "Seeded demo cache",
        "contact_name": None,
        "contact_email": None,
        "contact_phone": None,
        "days_on_market": 15,
        "listed_date": None,
        "listing_type": "Demo sale preview",
        "hoa_fee": 0,
        "mls_name": None,
        "mls_number": None,
        "market": {"median_price": 2400000, "median_price_per_sqft": 1120, "days_on_market": 14, "source": "Demo market snapshot"},
        "neighborhood": {
            "walkability": {"walkability_score": 84, "food": 15, "grocery": 5, "parks": 4, "transit": 5, "nearest_park_miles": 0.4, "nearest_grocery_miles": 0.2, "nearest_transit_miles": 0.4, "source": "Seeded demo amenity snapshot"},
            "schools": {"source": "Seeded demo school snapshot", "nearby_school_count": 8, "avg_rating_10": 9.4, "nearest_school_miles": 0.6, "schools": []},
            "crime": {"source": "Seeded demo safety snapshot", "safety_score": 80, "incidents_count": 6, "safety_label": "low reported incident signal"}
        },
        "commute": {},
        "scores": {},
        "reasons": ["Highest seeded school rating and strong commute orientation."]
    },
    {
        "id": "demo:campbell-townhome-007",
        "source": "demo_seed",
        "mode": "sale",
        "title": "Campbell luxury townhome",
        "address": "Demo home near Downtown Campbell",
        "city": "Campbell",
        "state": "CA",
        "zip_code": "95008",
        "latitude": 37.2860,
        "longitude": -121.9490,
        "distance_from_search_miles": None,
        "price": 1375000,
        "bedrooms": 3,
        "bathrooms": 3,
        "square_feet": 1985,
        "property_type": "Townhouse",
        "description": "Seeded demo cache record with a walkable dining district and light rail access.",
        "images": [
            "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?auto=format&fit=crop&w=1400&q=80",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1400&q=80"
        ],
        "source_url": None,
        "provider": "Seeded demo cache",
        "contact_name": None,
        "contact_email": None,
        "contact_phone": None,
        "days_on_market": 22,
        "listed_date": None,
        "listing_type": "Demo sale preview",
        "hoa_fee": 330,
        "mls_name": None,
        "mls_number": None,
        "market": {"median_price": 1385000, "median_price_per_sqft": 830, "days_on_market": 20, "source": "Demo market snapshot"},
        "neighborhood": {
            "walkability": {"walkability_score": 90, "food": 22, "grocery": 4, "parks": 5, "transit": 6, "nearest_park_miles": 0.2, "nearest_grocery_miles": 0.4, "nearest_transit_miles": 0.2, "source": "Seeded demo amenity snapshot"},
            "schools": {"source": "Seeded demo school snapshot", "nearby_school_count": 6, "avg_rating_10": 7.8, "nearest_school_miles": 0.5, "schools": []},
            "crime": {"source": "Seeded demo safety snapshot", "safety_score": 66, "incidents_count": 14, "safety_label": "moderate incident signal"}
        },
        "commute": {},
        "scores": {},
        "reasons": ["Lower entry price with strong walkability in the seeded cache."]
    },
    {
        "id": "demo:santa-clara-executive-008",
        "source": "demo_seed",
        "mode": "sale",
        "title": "Santa Clara executive home",
        "address": "Demo home near Central Park Santa Clara",
        "city": "Santa Clara",
        "state": "CA",
        "zip_code": "95051",
        "latitude": 37.3515,
        "longitude": -121.9854,
        "distance_from_search_miles": None,
        "price": 1985000,
        "bedrooms": 4,
        "bathrooms": 3,
        "square_feet": 2550,
        "property_type": "Single Family",
        "description": "Seeded demo cache record optimized for commute access to major South Bay employers.",
        "images": [
            "https://images.unsplash.com/photo-1600566753151-384129cf4e3e?auto=format&fit=crop&w=1400&q=80",
            "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=80"
        ],
        "source_url": None,
        "provider": "Seeded demo cache",
        "contact_name": None,
        "contact_email": None,
        "contact_phone": None,
        "days_on_market": 17,
        "listed_date": None,
        "listing_type": "Demo sale preview",
        "hoa_fee": 0,
        "mls_name": None,
        "mls_number": None,
        "market": {"median_price": 1660000, "median_price_per_sqft": 905, "days_on_market": 17, "source": "Demo market snapshot"},
        "neighborhood": {
            "walkability": {"walkability_score": 86, "food": 16, "grocery": 4, "parks": 5, "transit": 5, "nearest_park_miles": 0.2, "nearest_grocery_miles": 0.5, "nearest_transit_miles": 0.3, "source": "Seeded demo amenity snapshot"},
            "schools": {"source": "Seeded demo school snapshot", "nearby_school_count": 5, "avg_rating_10": 8.1, "nearest_school_miles": 0.8, "schools": []},
            "crime": {"source": "Seeded demo safety snapshot", "safety_score": 70, "incidents_count": 11, "safety_label": "moderate low incident signal"}
        },
        "commute": {},
        "scores": {},
        "reasons": ["Useful seeded comparison for South Bay employer commute tradeoffs."]
    },
    {
        "id": "demo:sunnyvale-modern-009",
        "source": "demo_seed",
        "mode": "sale",
        "title": "Sunnyvale renovated ranch",
        "address": "Demo home near Las Palmas Park",
        "city": "Sunnyvale",
        "state": "CA",
        "zip_code": "94087",
        "latitude": 37.3521,
        "longitude": -122.0364,
        "distance_from_search_miles": None,
        "price": 2350000,
        "bedrooms": 4,
        "bathrooms": 2.5,
        "square_feet": 2260,
        "property_type": "Single Family",
        "description": "Seeded demo cache record for buyers who care about commute, schools, and parks.",
        "images": [
            "https://images.unsplash.com/photo-1592595896551-12b371d546d5?auto=format&fit=crop&w=1400&q=80",
            "https://images.unsplash.com/photo-1600585152915-d208bec867a1?auto=format&fit=crop&w=1400&q=80"
        ],
        "source_url": None,
        "provider": "Seeded demo cache",
        "contact_name": None,
        "contact_email": None,
        "contact_phone": None,
        "days_on_market": 11,
        "listed_date": None,
        "listing_type": "Demo sale preview",
        "hoa_fee": 0,
        "mls_name": None,
        "mls_number": None,
        "market": {"median_price": 2050000, "median_price_per_sqft": 1025, "days_on_market": 13, "source": "Demo market snapshot"},
        "neighborhood": {
            "walkability": {"walkability_score": 82, "food": 14, "grocery": 3, "parks": 6, "transit": 5, "nearest_park_miles": 0.2, "nearest_grocery_miles": 0.5, "nearest_transit_miles": 0.4, "source": "Seeded demo amenity snapshot"},
            "schools": {"source": "Seeded demo school snapshot", "nearby_school_count": 7, "avg_rating_10": 8.9, "nearest_school_miles": 0.4, "schools": []},
            "crime": {"source": "Seeded demo safety snapshot", "safety_score": 77, "incidents_count": 8, "safety_label": "lower incident signal"}
        },
        "commute": {},
        "scores": {},
        "reasons": ["Strong seeded school and commute compromise within a wider San Jose radius."]
    },
    {
        "id": "demo:palo-alto-premium-010",
        "source": "demo_seed",
        "mode": "sale",
        "title": "Palo Alto premium contemporary",
        "address": "Demo home near Midtown Palo Alto",
        "city": "Palo Alto",
        "state": "CA",
        "zip_code": "94306",
        "latitude": 37.4180,
        "longitude": -122.1283,
        "distance_from_search_miles": None,
        "price": 4180000,
        "bedrooms": 4,
        "bathrooms": 3.5,
        "square_feet": 3050,
        "property_type": "Single Family",
        "description": "Seeded demo cache record for premium school and commute preference comparisons.",
        "images": [
            "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1400&q=80",
            "https://images.unsplash.com/photo-1600566752227-8f3b6d73d660?auto=format&fit=crop&w=1400&q=80"
        ],
        "source_url": None,
        "provider": "Seeded demo cache",
        "contact_name": None,
        "contact_email": None,
        "contact_phone": None,
        "days_on_market": 24,
        "listed_date": None,
        "listing_type": "Demo sale preview",
        "hoa_fee": 0,
        "mls_name": None,
        "mls_number": None,
        "market": {"median_price": 3350000, "median_price_per_sqft": 1450, "days_on_market": 19, "source": "Demo market snapshot"},
        "neighborhood": {
            "walkability": {"walkability_score": 88, "food": 20, "grocery": 5, "parks": 7, "transit": 5, "nearest_park_miles": 0.2, "nearest_grocery_miles": 0.4, "nearest_transit_miles": 0.5, "source": "Seeded demo amenity snapshot"},
            "schools": {"source": "Seeded demo school snapshot", "nearby_school_count": 9, "avg_rating_10": 9.3, "nearest_school_miles": 0.5, "schools": []},
            "crime": {"source": "Seeded demo safety snapshot", "safety_score": 78, "incidents_count": 7, "safety_label": "lower incident signal"}
        },
        "commute": {},
        "scores": {},
        "reasons": ["Premium seeded option for the upper budget edge of a wide commute radius."]
    },
    {
        "id": "demo:sj-95123-rental-011",
        "source": "demo_seed",
        "mode": "rental",
        "title": "Blossom Valley executive rental",
        "address": "Demo rental near Blossom Hill Caltrain connector",
        "city": "San Jose",
        "state": "CA",
        "zip_code": "95123",
        "latitude": 37.2472,
        "longitude": -121.8239,
        "distance_from_search_miles": None,
        "price": 5200,
        "bedrooms": 4,
        "bathrooms": 3,
        "square_feet": 2250,
        "property_type": "Single Family",
        "description": "Seeded demo rental cache record for relocation renters who need bedrooms, parks, and commute context.",
        "images": [
            "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=1400&q=80",
            "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=1400&q=80"
        ],
        "source_url": None,
        "provider": "Seeded demo cache",
        "contact_name": None,
        "contact_email": None,
        "contact_phone": None,
        "days_on_market": 6,
        "listed_date": None,
        "listing_type": "Demo rental preview",
        "hoa_fee": None,
        "mls_name": None,
        "mls_number": None,
        "market": {"median_price": 4300, "median_price_per_sqft": 2.9, "days_on_market": 12, "source": "Demo market snapshot"},
        "neighborhood": {
            "walkability": {"walkability_score": 78, "food": 10, "grocery": 2, "parks": 5, "transit": 4, "nearest_park_miles": 0.3, "nearest_grocery_miles": 0.6, "nearest_transit_miles": 0.4, "source": "Seeded demo amenity snapshot"},
            "schools": {"source": "Seeded demo school snapshot", "nearby_school_count": 5, "avg_rating_10": 8.0, "nearest_school_miles": 0.6, "schools": []},
            "crime": {"source": "Seeded demo safety snapshot", "safety_score": 74, "incidents_count": 9, "safety_label": "moderate low incident signal"}
        },
        "commute": {},
        "scores": {},
        "reasons": ["Rental seeded cache record for user flows that switch from buying to renting."]
    }
]


def demo_seed_listings(mode: str | None = None) -> list[dict[str, Any]]:
    records = [item for item in SAN_JOSE_LUXURY_DEMO_LISTINGS if mode is None or item.get("mode") == mode]
    output: list[dict[str, Any]] = []
    for item in records:
        record = deepcopy(item)
        record.setdefault("raw", {"source_note": "Seeded cache record. Not a live MLS or RentCast listing."})
        output.append(record)
    return output
